-- 週次レポート（工事部員配置状況）の本文アーカイブ（HTML＋PDF）。
--
--   allocation_reports … 現場人員配置タブの「週次レポート」出力時に、その週のHTML本文と
--                        PDF（base64）を丸ごと保存し、後から一覧で参照・再ダウンロードできる
--                        ようにする。数値だけの allocation_snapshots とは別（本文は重いため）。
--                        同じ週(taken_on)の再出力は upsert で上書き。
--
-- 閲覧範囲＝現場人員配置タブ(gantt)を見られる全ロールと同じ
-- （admin/editor/executive/manager/viewer/accounting＝実質ログイン済み全員）なので
-- authenticated全許可でよい。書込は allocation_snapshots と同じ admin+editor。
--
-- 前提：phaseE1a_roles.sql 実行済み（app_role() が存在）。
-- 使い方：Supabase ダッシュボード → SQL Editor に貼り付け → Run。冪等。

create table if not exists public.allocation_reports (
  id           bigint generated by default as identity primary key,
  taken_on     date not null,             -- 対象週（レポートの基準日＝直近の月曜）
  title        text,                      -- 表示タイトル（例: 工事部員配置状況（2026.7.13））
  html_content text not null,             -- 自己完結HTML全文
  pdf_base64   text,                      -- PDF（data:application/pdf;base64,... 形式）。生成失敗時はnull許容
  created_at   timestamptz default now(),
  created_by   text
);

-- 同じ週は1行（アプリ側 upsert の onConflict と一対）
create unique index if not exists uq_alloc_reports_taken_on on public.allocation_reports(taken_on);

-- 一覧取得（メタのみ）を速くするための索引
create index if not exists idx_alloc_reports_taken_on_desc on public.allocation_reports(taken_on desc);

-- ===== RLS =====
alter table public.allocation_reports enable row level security;

drop policy if exists read_alloc_reports on public.allocation_reports;
create policy read_alloc_reports on public.allocation_reports
  for select to authenticated using (true);

drop policy if exists ins_alloc_reports on public.allocation_reports;
create policy ins_alloc_reports on public.allocation_reports
  for insert to authenticated with check (app_role() in ('admin', 'editor'));

drop policy if exists upd_alloc_reports on public.allocation_reports;
create policy upd_alloc_reports on public.allocation_reports
  for update to authenticated
  using (app_role() in ('admin', 'editor'))
  with check (app_role() in ('admin', 'editor'));

drop policy if exists del_alloc_reports on public.allocation_reports;
create policy del_alloc_reports on public.allocation_reports
  for delete to authenticated using (app_role() = 'admin');
