-- 週次レポート（工事部員配置状況）のサマリー数値スナップショット。
--
--   allocation_snapshots … 現場人員配置タブの「週次レポート」出力時に
--                          事務所別1行＋合計「計」1行を記録し、稼働率の時系列推移分析に使う。
--                          同日・同事務所の再出力は upsert で上書き（週次運用で二重行にならない）。
--
-- 集計定義（js/views/gantt/report.js と一対。変更時は両方を同期すること）:
--   supervisors = 「〜事務所」所属の現場監督＋準現場監督
--   active_m0/m3/m6/m9 = 当月・+3/+6/+9ヶ月に1日でも配置バーが重なる監督数
--                     （準備期間prep_start〜joinも稼働・完成工事除外・見込み案件含む）。
--                     当月は確定値、+3/+6/+9は稼働予定。
--                     専従・派遣（稼働形態）は配置バーが無くても稼働に含む
--                     （期間設定があればその期間と重なる月のみ・2026-07-10定義確定）
--   month_m0 = 当月（YYYY/MM テキスト）。m3/m6/m9 はここから機械的に導ける
--
-- RLS：読=authenticated／書=admin+editor。
-- 前提：phaseE1a_roles.sql 実行済み（app_role() が存在）。
-- 使い方：Supabase ダッシュボード → SQL Editor に貼り付け → Run。冪等。
-- ⚠️ policy の更新は必ず drop→create をワンセットで実行（dropだけ通るとアクセス不能になる）。

create table if not exists public.allocation_snapshots (
  id           bigint generated by default as identity primary key,
  taken_on     date not null,             -- スナップショット日（出力日）
  office       text not null,             -- 事務所名（本社事務所 等）。合計行は「計」
  supervisors  int  not null,             -- 監督者数（現場監督＋準現場監督）
  month_m0     text not null,             -- 当月（YYYY/MM）
  active_m0    int  not null,             -- 当月稼働
  active_m3    int  not null,             -- +3ヶ月稼働予定
  active_m6    int  not null,             -- +6ヶ月稼働予定
  active_m9    int  not null default 0,    -- +9ヶ月稼働予定
  created_at   timestamptz default now(),
  created_by   text
);

-- 既にテーブルが存在する環境向け（create table if not existsは既存テーブルには無効なため、
-- 列追加は明示的なALTERで担保する。新規作成時は上のcreate table側に列があるため実質no-op）。
alter table public.allocation_snapshots add column if not exists active_m9 int not null default 0;

-- 同日・同事務所は1行（アプリ側 upsert の onConflict と一対）
create unique index if not exists uq_alloc_snap on public.allocation_snapshots(taken_on, office);

-- ===== RLS =====
alter table public.allocation_snapshots enable row level security;

drop policy if exists read_alloc_snap  on public.allocation_snapshots;
create policy read_alloc_snap  on public.allocation_snapshots
  for select to authenticated using (true);

drop policy if exists ins_alloc_snap on public.allocation_snapshots;
create policy ins_alloc_snap on public.allocation_snapshots
  for insert to authenticated with check (app_role() in ('admin', 'editor'));

drop policy if exists upd_alloc_snap on public.allocation_snapshots;
create policy upd_alloc_snap on public.allocation_snapshots
  for update to authenticated
  using (app_role() in ('admin', 'editor'))
  with check (app_role() in ('admin', 'editor'));
