-- 社内連絡先（電話番号表＋事業所情報）テーブル
-- 出典: 総務発行の「電話番号表」PDF ＋ 会社公式サイト アクセスページ（事業所住所・TEL・FAX）。
-- データ投入は Box 側の seed SQL で行う
-- （⚠️このリポジトリは Public のため、実際の氏名・電話番号はコミットしない。
--   seed の置き場所 = Box\...\ツール【統合管理】\自動化\連絡先取込\）。
--
-- section: 'extension'=本社内線 / 'mobile'=社用携帯 / 'office'=本社フロア直通 /
--          'branch'=事業所（本社・各事務所・作業所の住所/TEL/FAX） / 'meta'=基準日等
-- group_name: extension=部署名（先頭の役員ブロックは空文字） / mobile=五十音行（あ/か/さ…） / それ以外=空文字
-- sort_order: 原本の記載順を保持（内線=番号順・携帯=五十音順）
create table if not exists contacts (
  id bigint generated by default as identity primary key,
  section text not null,
  group_name text not null default '',
  name text not null,
  number text not null default '',
  address text not null default '',
  fax text not null default '',
  sort_order integer not null default 0,
  note text not null default ''
);

-- v1(2026-07-15初版)を実行済みの環境にも列と制約を後付けできるようにする
alter table contacts add column if not exists address text not null default '';
alter table contacts add column if not exists fax text not null default '';
alter table contacts drop constraint if exists contacts_section_check;
alter table contacts add constraint contacts_section_check
  check (section in ('extension', 'mobile', 'office', 'branch', 'meta'));

alter table contacts enable row level security;

-- 閲覧 = ログイン済み全ロール（社内電話帳のため）。
-- 書込ポリシーは意図的に作らない = クライアントからは一切書込不可
-- （更新は総務PDFの改版時に SQL Editor で seed を再実行する運用）。
drop policy if exists read_contacts on contacts;
create policy read_contacts on contacts for select to authenticated using (true);
