-- 不在（長期休暇・休職・育休・産休・その他）の登録テーブル。
--
--   employee_absences … 1人が複数期間を持てる（employee_tiers は emp_no 主キーで1行のため不可）。
--                       監督ダッシュボードで登録 → 監督軸・事務所モニターでグレーの網掛け帯
--                       「育休中 約6か月」等を表示。不在期間は「空き」帯を抑制する（占有扱い）。
--                       配置データ（assignments）には影響しない＝見える化のみ。
--
-- 全列 text（id のみサロゲート）。kind は 長期休暇/休職/育休/産休/その他。
-- start_date / end_date は YYYY/MM/DD のテキスト。
-- RLS：読=anon+authenticated／書=authenticated（編集ログイン中のみ）。
-- 使い方：Supabase ダッシュボード → SQL Editor に貼り付け → Run。冪等。

create table if not exists public.employee_absences (
  id          bigint generated by default as identity primary key,
  emp_no      text not null,
  kind        text not null,
  start_date  text,
  end_date    text,
  note        text,
  updated_at  timestamptz default now(),
  updated_by  text
);

create index if not exists idx_absences_emp on public.employee_absences(emp_no);

-- ===== RLS =====（policy は drop-if-exists 付きで再実行しても安全）
alter table public.employee_absences enable row level security;

drop policy if exists read_absences  on public.employee_absences;
drop policy if exists w_absences_ins  on public.employee_absences;
drop policy if exists w_absences_upd  on public.employee_absences;
drop policy if exists w_absences_del  on public.employee_absences;

create policy read_absences  on public.employee_absences for select to anon, authenticated using (true);
create policy w_absences_ins on public.employee_absences for insert to authenticated with check (true);
create policy w_absences_upd on public.employee_absences for update to authenticated using (true) with check (true);
create policy w_absences_del on public.employee_absences for delete to authenticated using (true);
