-- 段階D（組織図・階層判定）: 新テーブル2つ。既存テーブルには一切触れない。
--
--   organization    … SmartHR名簿(01_organization)を同期で全置換。組織構造の正。
--   employee_tiers  … 社員番号×階層の判定結果。アプリ(組織図画面)が書き込む。
--                     旧 01_employees の 区分/中計 列を置き換える。
--
-- 全列 text（depts/positions のみ jsonb 配列）。RLS：読=anon+authenticated／書=authenticated。
-- 使い方：SQL Editor に貼り付け → Run。

-- ===== organization（SmartHR名簿・同期で全置換） =====
create table if not exists public.organization (
  id         bigint generated by default as identity primary key,
  emp_no     text,          -- 社員番号（実質キー・unique制約は付けない＝同期の投入→旧削除順を阻害しないため）
  last_name  text,          -- 姓
  first_name text,          -- 名
  kana_last  text,
  kana_first text,
  email      text,
  business   text,          -- 業務内容
  hire_date  text,          -- 入社年月日
  depts      jsonb,         -- 非空の部署1..10（スラッシュ階層パスの配列）
  positions  jsonb          -- 非空の役職1..10
);

-- ===== employee_tiers（階層判定・アプリが書く） =====
create table if not exists public.employee_tiers (
  emp_no     text primary key,
  tier       text,          -- 監督職 / 準監督職 / 広義監督職 / 対象外
  note       text,
  updated_at text,
  updated_by text
);

-- ===== RLS =====
alter table public.organization   enable row level security;
alter table public.employee_tiers enable row level security;

-- 読み取り：anon + authenticated
create policy read_org   on public.organization   for select to anon, authenticated using (true);
create policy read_tiers on public.employee_tiers for select to anon, authenticated using (true);

-- 書き込み：authenticated のみ（organization=同期で全置換／employee_tiers=組織図画面でupsert）
create policy w_org_ins   on public.organization   for insert to authenticated with check (true);
create policy w_org_del   on public.organization   for delete to authenticated using (true);

create policy w_tiers_ins on public.employee_tiers for insert to authenticated with check (true);
create policy w_tiers_upd on public.employee_tiers for update to authenticated using (true) with check (true);
create policy w_tiers_del on public.employee_tiers for delete to authenticated using (true);
