-- 段階E4a（安全Eラーニング）: 出題テーブル quiz_questions ＋ 解答ログ quiz_answers
--
-- コンセプト：毎朝、現場に入る前の4択10〜20問。続ければ伸びる、サボれば見える。
--   - quiz_questions … 出題本体（4択＋正解＋解説＋出典）。書込は admin のみ（出題管理画面）。
--   - quiz_answers   … 1解答=1行の学習ログ。本人だけが書き込め、本人＋管理職/経営者が閲覧。
--
-- 権限モデル（RLS サーバー強制）：
--   quiz_questions  SELECT = ログイン済み全員（ただし非公開は admin のみ）/ 書込 = admin
--   quiz_answers    INSERT = 本人(user_id=auth.uid())のみ / SELECT = 本人 ＋ admin/manager/executive
--                   ＝ 学習者は自分の記録しか見えず・消せず、管理職は全員分を見られる（サボりが見える）
--
-- 前提：phaseE1a_roles.sql 実行済み（user_roles / app_role() security definer が存在）。
-- 使い方：Supabase ダッシュボード → SQL Editor に貼り付け → Run。
--   その後 phaseE4_seed_questions.sql を実行して初期問題（安全のしおり）を投入。
-- ロールバック：drop table public.quiz_answers; drop table public.quiz_questions;

-- ============================================================
-- 1. quiz_questions（出題本体）
-- ============================================================
create table if not exists public.quiz_questions (
  id          bigint generated by default as identity primary key,
  qid         text unique not null,                                  -- 'SHIORI-001' 安定キー（Excel/再シードと対応）
  unit        text not null,                                         -- 安全のしおり / 規程類 / ベステラスタンダード / 過去事例
  sub         text,                                                  -- 中分類（節・テーマ）
  difficulty  text,                                                  -- '★' / '★★' / '★★★'
  question    text not null,
  choice_a    text not null,
  choice_b    text not null,
  choice_c    text not null,
  choice_d    text not null,
  correct     text not null check (correct in ('A','B','C','D')),
  explanation text,                                                  -- 解説（正解の根拠＋重要ポイント）
  source      text,                                                  -- 出典（資料名＋該当箇所）
  active      boolean not null default true,                         -- 公開フラグ（非公開＝学習者には出さない）
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

create index if not exists idx_quiz_questions_unit on public.quiz_questions (unit, active);

alter table public.quiz_questions enable row level security;

drop policy if exists q_read   on public.quiz_questions;
drop policy if exists q_ins    on public.quiz_questions;
drop policy if exists q_upd    on public.quiz_questions;
drop policy if exists q_del    on public.quiz_questions;

-- 読取：ログイン済みなら公開問題を読める。admin は非公開も読める（出題管理・精査用）。
create policy q_read on public.quiz_questions for select to authenticated
  using (active = true or app_role() = 'admin');
-- 書込：admin のみ
create policy q_ins on public.quiz_questions for insert to authenticated with check (app_role() = 'admin');
create policy q_upd on public.quiz_questions for update to authenticated using (app_role() = 'admin') with check (app_role() = 'admin');
create policy q_del on public.quiz_questions for delete to authenticated using (app_role() = 'admin');

-- ============================================================
-- 2. quiz_answers（解答ログ・1解答=1行）
-- ============================================================
create table if not exists public.quiz_answers (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null default auth.uid() references auth.users(id) on delete cascade,
  question_id bigint references public.quiz_questions(id) on delete set null,
  qid         text,                                                  -- 冗長保持（問題が消えても履歴に残す）
  unit        text,
  choice      text check (choice in ('A','B','C','D')),
  is_correct  boolean,
  answered_at timestamptz not null default now()
);

create index if not exists idx_quiz_answers_user_time on public.quiz_answers (user_id, answered_at desc);
create index if not exists idx_quiz_answers_question  on public.quiz_answers (question_id);

alter table public.quiz_answers enable row level security;

drop policy if exists a_ins  on public.quiz_answers;
drop policy if exists a_read on public.quiz_answers;
drop policy if exists a_del  on public.quiz_answers;

-- 書込：本人の行のみ INSERT 可（user_id は default auth.uid() で自動。改ざんで他人名義は弾く）。
create policy a_ins  on public.quiz_answers for insert to authenticated with check (user_id = auth.uid());
-- 読取：本人 ＋ 管理職/経営者/管理者（全社モニタリング）。editor/viewer は自分の分のみ。
create policy a_read on public.quiz_answers for select to authenticated
  using (user_id = auth.uid() or app_role() in ('admin','manager','executive'));
-- 削除：admin のみ（学習者は自分の記録も消せない）。
create policy a_del  on public.quiz_answers for delete to authenticated using (app_role() = 'admin');
