-- 段階D5（資格統合・01_employees 廃止）: 新テーブル employee_quals。
--
--   employee_quals … Sheets の「02_employees」タブ(社員番号/名前/資格)を同期で全置換。資格の正。
--                    旧 employees(01_employees) の F列「資格」依存をこれで置き換える。
--                    将来 SmartHR の資格データで列が増える前提（増えた列は
--                    sync.js の REFERENCE_COLUMNS.employee_quals に追記して取り込む）。
--
-- 全列 text（id のみサロゲート）。同期の「先に投入→旧行削除」全置換には id が必須。
-- RLS：読=anon+authenticated／書=authenticated（同期＝編集者のみ）。
-- 使い方：Supabase ダッシュボード → SQL Editor に貼り付け → Run。

create table if not exists public.employee_quals (
  id         bigint generated by default as identity primary key,
  "社員番号" text,
  "名前"     text,
  "資格"     text
);

-- ===== RLS =====（policy は drop-if-exists 付きで再実行しても安全）
alter table public.employee_quals enable row level security;

drop policy if exists read_quals  on public.employee_quals;
drop policy if exists w_quals_ins on public.employee_quals;
drop policy if exists w_quals_del on public.employee_quals;

create policy read_quals  on public.employee_quals for select to anon, authenticated using (true);
create policy w_quals_ins on public.employee_quals for insert to authenticated with check (true);
create policy w_quals_del on public.employee_quals for delete to authenticated using (true);
