-- 段階Q（資格情報の詳細化）: employee_quals を SmartHR「従業員の資格一覧」エクスポート形に作り直す。
--
-- 旧 employee_quals（社員番号/名前/資格・1行=1人）→ 新（1行=1人×1資格・取得日/有効期限つき）。
-- データの正は Google Sheets「02_employees」タブ（SmartHRエクスポートを貼付）。同期(admin)で全置換。
--
-- ⚠️ 本番コード(feature/qualifications)のmainマージと同時に実行すること。
--    旧コードは 名前/資格 列を読むため、先に作り直すと本番の資格表示が一時的に空になる。
-- バックアップ: 旧データは besterra-allocation-backups/2026-05-26_supabase/employee_quals.json（109行）。
-- ロールバック: phaseD5_schema.sql で旧スキーマ再作成 ＋ 上記JSONを投入。
--
-- 使い方: Supabase SQL Editor に貼付 → Run。

drop table if exists public.employee_quals;

create table public.employee_quals (
  id         bigint generated by default as identity primary key,
  "社員番号" text,
  "氏名"     text,
  "コード"   text,   -- 資格名（プレーン）
  "保有資格" text,   -- "種別/資格名"（種別 = 資格 / 技能講習 / 特別教育 等）
  "取得日"   text,
  "有効期限" text    -- "期限なし" または "YYYY/M/D"
);

-- RLS（カットオーバー後の権限モデル：読=authenticated / 書=admin のみ）
alter table public.employee_quals enable row level security;
drop policy if exists read_quals  on public.employee_quals;
drop policy if exists w_quals_ins on public.employee_quals;
drop policy if exists w_quals_del on public.employee_quals;
create policy read_quals  on public.employee_quals for select to authenticated using (true);
create policy w_quals_ins on public.employee_quals for insert to authenticated with check (app_role() = 'admin');
create policy w_quals_del on public.employee_quals for delete to authenticated using (app_role() = 'admin');
