-- 段階E3（経営ドッキング）: 経営レポート格納テーブル management_reports
--
-- ★ このツールに初めて「経営機密」が入る段階。RLS強制が airtight であることが前提。
--   R/F 分析資料・月次経営分析レポートの「生成済HTML」を本テーブルに格納し、
--   アプリは html_content を Blob URL 化して iframe 表示する。
--   レポート実体は 公開リポジトリ・公開URL には一切置かない（ここが機密の肝）。
--
-- 権限モデル（カットオーバー後）：
--   - SELECT = admin / executive のみ（経営者と管理者だけが閲覧できる）
--   - INSERT/UPDATE/DELETE = admin のみ（admin がアプリ内アップロードで月次差替）
--   ※ E1b で他テーブルは authenticated 全許可だが、本テーブルは app_role() で
--     さらに admin/executive に絞る。manager/editor/viewer はログイン済みでも読めない。
--
-- 月次履歴：(report_type, year_month) を UNIQUE にし、同月の再アップロードは upsert で差替。
--
-- 前提：phaseE1a_roles.sql 実行済み（user_roles / app_role() security definer が存在）。
-- 使い方：Supabase ダッシュボード → SQL Editor に貼り付け → Run。
-- ロールバック：drop table public.management_reports;（機密データも消えるので注意）

create table if not exists public.management_reports (
  id           bigint generated by default as identity primary key,
  report_type  text not null check (report_type in ('analysis', 'rf')),  -- analysis=月次経営分析 / rf=ローリングフォーキャスト
  year_month   text not null,                                            -- 'YYYYMM'（例 '202602'）
  title        text,                                                     -- 任意の表示タイトル
  html_content text not null,                                            -- 生成済HTML全文（自己完結・外部依存はChart.js CDNのみ）
  uploaded_at  timestamptz default now(),
  uploaded_by  text,                                                     -- アップロードした admin の email
  unique (report_type, year_month)
);

-- 一覧取得（メタのみ）を速くするための索引
create index if not exists idx_mgmt_reports_type_ym
  on public.management_reports (report_type, year_month desc);

-- ============================================================
-- RLS：閲覧=admin/executive・書込=admin のみ
-- ============================================================
alter table public.management_reports enable row level security;

drop policy if exists read_mgmt   on public.management_reports;
drop policy if exists w_mgmt_ins  on public.management_reports;
drop policy if exists w_mgmt_upd  on public.management_reports;
drop policy if exists w_mgmt_del  on public.management_reports;

create policy read_mgmt  on public.management_reports for select to authenticated using (app_role() in ('admin', 'executive'));
create policy w_mgmt_ins on public.management_reports for insert to authenticated with check (app_role() = 'admin');
create policy w_mgmt_upd on public.management_reports for update to authenticated using (app_role() = 'admin') with check (app_role() = 'admin');
create policy w_mgmt_del on public.management_reports for delete to authenticated using (app_role() = 'admin');
