-- besterra-allocation : Supabase スキーマ（段階A：現行 Google Sheets の忠実な写し）
--
-- 方針：
--   - 全列 text 型。型変換は従来どおり JS（sync.js）側で行うため、ここでは一切変換しない。
--     （社員番号の先頭ゼロ・"TRUE"/"FALSE"・"2026/09/01" 形式・"JPY440,000" などをそのまま保持）
--   - 列名は現行シートと完全一致（日本語列はそのまま。JS が同じキーで読むため無改修で動く）。
--   - salesforce_imports のみ、parseSalesforceCsv の「整形後」スキーマで保存する
--     （生レポート形式ではなく、deriveFromSalesforce が直接消費できる形）。
--   - RLS は段階A では無効のまま（既定）。段階B で Auth と同時に有効化する。
--
-- 使い方：Supabase ダッシュボード → SQL Editor に全文貼り付け → Run。

-- ===== 01 employees（社員マスタ） =====
-- ⚠️ 段階D6で廃止・物理削除済み（phaseD6_drop_employees.sql）。
--    社員の正は organization+employee_tiers（phaseD_schema.sql）、資格の正は employee_quals。
--    以下の CREATE は段階A当時の記録として残置（再実行すると不要なテーブルが復活するので注意）。
create table if not exists public.employees (
  id                  bigint generated by default as identity primary key,
  "No"                text,
  "社員番号"          text,
  "名前"              text,
  "部門"              text,
  "役職"              text,
  "資格"              text,
  "区分"              text,
  "中計"              text,
  "所属（最終判定）"  text,
  "オーバーライド理由" text,
  "ユーザーチェック"  text
);

-- ===== 09 salesforce_imports（parseSalesforceCsv 整形後の形で保存） =====
create table if not exists public.salesforce_imports (
  id            bigint generated by default as identity primary key,
  department    text,
  emp_name      text,
  emp_name_raw  text,
  role          text,
  role_detail   text,
  contract_type text,
  project_id    text,
  project_name  text,
  "start"       text,
  "end"         text,
  total_revenue text,
  order_amount  text,
  status        text
);

-- ===== 11 prospects（見込み案件・アプリから CRUD） =====
create table if not exists public.prospects (
  prospect_id   text primary key,
  status        text,
  customer      text,
  project_name  text,
  contract_type text,
  area          text,
  managing_dept text,
  start_date    text,
  end_date      text,
  amount        text,
  note          text,
  created_at    text,
  updated_at    text,
  updated_by    text,
  archived      text
);

-- ===== 12 assignment_overrides（配属の上書き差分・アプリから upsert/delete） =====
create table if not exists public.assignment_overrides (
  override_key text primary key,
  emp_name     text,
  project_id   text,
  join_date    text,
  planned_end  text,
  role         text,
  note         text,
  updated_at   text,
  updated_by   text,
  op           text
);

-- ===== 07 g_work_logs（勤怠ログ・読み取り専用の集計ソース） =====
create table if not exists public.g_work_logs (
  id               bigint generated by default as identity primary key,
  "社員コード"     text,
  "社員名"         text,
  "日付"           text,
  "勤務時間差異"   text,
  "プロジェクトコード" text,
  "プロジェクト名" text,
  "作業時間"       text,
  "備考"           text
);

-- ===== 13 project_status_overrides（完成/進行中の手動上書き・アプリから upsert/delete） =====
create table if not exists public.project_status_overrides (
  project_id text primary key,
  completed  text,
  note       text,
  updated_at text,
  updated_by text
);

-- 段階B（Auth導入時）で以下を有効化する想定：
--   alter table public.<each> enable row level security;
--   + viewer=SELECTのみ / editor=全権 のポリシー
-- 段階A では RLS 無効のままで OK（ダッシュボードの "RLS disabled" 警告は想定どおり）。
